name: material_color_scheme
description: A tool for easily making material and flutter color schemes.
version: 0.0.1
author: Stefan Rusek <stefan@ergonlabs.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
